const ERROR_STATUS: Record<string, number> = {
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  INVALID_REFRESH_TOKEN: 401,
  INVALID_ACTIVATION_TOKEN: 400,
  PASSWORD_CHANGE_REQUIRED: 403,
  ACCOUNT_DISABLED: 403,
  ACCOUNT_PENDING_ACTIVATION: 403,
  COMPANY_DISABLED: 403,
  CSRF_TOKEN_INVALID: 403,
  RATE_LIMITED: 429,

  INSUFFICIENT_PERMISSION: 403,
  TENANT_ACCESS_DENIED: 403,
  FEATURE_NOT_ENABLED: 403,

  VALIDATION_ERROR: 400,
  RESOURCE_NOT_FOUND: 404,
  CONFLICT: 409,

  INVALID_DASHBOARD_ID: 400,
  DASHBOARD_NOT_FOUND: 404,
  INVALID_FILTER: 400,
  DASHBOARD_SOURCE_UNAVAILABLE: 503,

  CONNECTOR_AUTH_FAILED: 400,
  CONNECTOR_UNREACHABLE: 502,

  EMAIL_DELIVERY_FAILED: 502,
  SERVICE_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
};

const DISCLOSED_SERVER_ERRORS = new Set([
  'EMAIL_DELIVERY_FAILED',
  'SERVICE_UNAVAILABLE',
  'DASHBOARD_SOURCE_UNAVAILABLE',
  'CONNECTOR_UNREACHABLE',
]);

const SAFE_TO_DISCLOSE = new Set([
  ...Object.keys(ERROR_STATUS).filter((code) => ERROR_STATUS[code] < 500),
  ...DISCLOSED_SERVER_ERRORS,
]);

const GENERIC_MESSAGE = 'Something went wrong on our side. Please try again.';

export { ERROR_STATUS, SAFE_TO_DISCLOSE, GENERIC_MESSAGE };
