const UNIQUE_VIOLATION = '23505';
const FOREIGN_KEY_VIOLATION = '23503';
const INVALID_TEXT_REPRESENTATION = '22P02';
const UNDEFINED_TABLE = '42P01';

export {
  UNIQUE_VIOLATION,
  FOREIGN_KEY_VIOLATION,
  INVALID_TEXT_REPRESENTATION,
  UNDEFINED_TABLE,
};
