const SECOND = 1;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

const ACCESS_TOKEN_TTL_SECONDS = 15 * MINUTE;

const REFRESH_TOKEN_TTL_SECONDS = 30 * DAY;

const ACTIVATION_TOKEN_TTL_SECONDS = 72 * HOUR;

const LOGIN_MAX_ATTEMPTS = 10;
const LOGIN_WINDOW_SECONDS = 15 * MINUTE;
const LOGIN_LOCKOUT_SECONDS = 15 * MINUTE;

const QUERY_CONCURRENCY = 6;

const BOOTSTRAP_SUPERADMIN = {
  username: 'platformowner',
  email: 'owner@example.com',
  password: 'ChangeMeAtFirstSignIn1!',
};

export {
  ACCESS_TOKEN_TTL_SECONDS,
  REFRESH_TOKEN_TTL_SECONDS,
  ACTIVATION_TOKEN_TTL_SECONDS,
  LOGIN_MAX_ATTEMPTS,
  LOGIN_WINDOW_SECONDS,
  LOGIN_LOCKOUT_SECONDS,
  QUERY_CONCURRENCY,
  BOOTSTRAP_SUPERADMIN,
};
