import { quoteIdentifier } from '../tools/sql';
import { ACCESS_LEVELS } from '../constants/permissions';
import { USER_STATUS } from '../constants/statuses';

const q = quoteIdentifier;
const T = {
  companies: q('companies'),
  users: q('users'),
  roles: q('roles'),
  rolePermissions: q('role_permissions'),
  groups: q('groups'),
  groupUsers: q('group_users'),
  companyDashboards: q('company_dashboards'),
  dashboards: q('dashboards'),
  dashboardAccess: q('dashboard_access'),
  groupDashboardAccess: q('group_dashboard_access'),
  userDataScope: q('user_data_scope'),
  refreshTokens: q('refresh_tokens'),
  userTokens: q('user_tokens'),
  loginAttempts: q('login_attempts'),
  permissionSeedLog: q('permission_seed_log'),
  rbacRepairs: q('rbac_repairs'),
  auditLogs: q('audit_logs'),
  companyFeatures: q('company_features'),
  companyRoles: q('company_roles'),
  companyRolePermissions: q('company_role_permissions'),
  permissions: q('permissions'),
};

const LEVEL_LIST = ACCESS_LEVELS.map((level) => `'${level}'`).join(',');

const STATUS_LIST = [USER_STATUS.PENDING, USER_STATUS.ACTIVE, USER_STATUS.DISABLED]
  .map((s) => `'${s}'`)
  .join(',');

const TABLES = [
  `CREATE TABLE IF NOT EXISTS ${T.companies} (
     id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name         VARCHAR(150) NOT NULL,
     slug         VARCHAR(64)  NOT NULL,
     active       BOOLEAN      NOT NULL DEFAULT TRUE,
     created_by   INTEGER      NULL,
     created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
     CONSTRAINT uq_companies_slug UNIQUE (slug),
     CONSTRAINT uq_companies_name UNIQUE (name)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.users} (
     id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     company_id           INTEGER      NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     username             VARCHAR(50)  NOT NULL,
     email                VARCHAR(190) NOT NULL,
     display_name         VARCHAR(120) NULL,
     password_hash        VARCHAR(100) NULL,
     role                 VARCHAR(50)  NOT NULL,
     status               VARCHAR(16)  NOT NULL DEFAULT 'pending',
     must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
     last_login_at        TIMESTAMPTZ  NULL,
     created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
     CONSTRAINT uq_users_username UNIQUE (username),
     CONSTRAINT uq_users_email    UNIQUE (email),
     CONSTRAINT chk_users_status  CHECK (status IN (${STATUS_LIST}))
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.roles} (
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name        VARCHAR(50) NOT NULL,
     scope       VARCHAR(16) NOT NULL DEFAULT 'company',
     description VARCHAR(255) NULL,
     created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
     CONSTRAINT uq_roles_name UNIQUE (name),
     CONSTRAINT chk_roles_scope CHECK (scope IN ('platform','company'))
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.rolePermissions} (
     role_name     VARCHAR(50)  NOT NULL
                     REFERENCES ${T.roles} (name) ON DELETE CASCADE ON UPDATE CASCADE,
     permission_id VARCHAR(100) NOT NULL,
     PRIMARY KEY (role_name, permission_id)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.groups} (
     id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     company_id INTEGER      NOT NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     name       VARCHAR(100) NOT NULL,
     active     BOOLEAN      NOT NULL DEFAULT TRUE,
     creator_id INTEGER      NULL REFERENCES ${T.users} (id) ON DELETE SET NULL,
     created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
     CONSTRAINT uq_groups_company_name UNIQUE (company_id, name)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.groupUsers} (
     group_id   INTEGER     NOT NULL REFERENCES ${T.groups} (id) ON DELETE CASCADE,
     user_id    INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (group_id, user_id)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.dashboards} (
     id           VARCHAR(64)  PRIMARY KEY,
     title        VARCHAR(150) NOT NULL,
     description  TEXT         NULL,
     company_id   INTEGER      NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     created_by   INTEGER      NULL REFERENCES ${T.users} (id) ON DELETE SET NULL,
     spec         JSONB        NOT NULL,
     created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
     updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.companyDashboards} (
     company_id   INTEGER     NOT NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     dashboard_id VARCHAR(64) NOT NULL,
     assigned_by  INTEGER     NULL,
     assigned_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (company_id, dashboard_id)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.dashboardAccess} (
     user_id      INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     dashboard_id VARCHAR(64) NOT NULL,
     access_level VARCHAR(10) NOT NULL DEFAULT 'view',
     granted_by   INTEGER     NULL,
     granted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (user_id, dashboard_id),
     CONSTRAINT chk_dashboard_access_level CHECK (access_level IN (${LEVEL_LIST}))
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.groupDashboardAccess} (
     group_id     INTEGER     NOT NULL REFERENCES ${T.groups} (id) ON DELETE CASCADE,
     dashboard_id VARCHAR(64) NOT NULL,
     access_level VARCHAR(10) NOT NULL DEFAULT 'view',
     granted_by   INTEGER     NULL,
     granted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (group_id, dashboard_id),
     CONSTRAINT chk_group_dashboard_access_level CHECK (access_level IN (${LEVEL_LIST}))
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.userDataScope} (
     user_id    INTEGER      NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     dimension  VARCHAR(64)  NOT NULL,
     value      VARCHAR(120) NOT NULL,
     created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
     PRIMARY KEY (user_id, dimension, value)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.refreshTokens} (
     id             UUID        PRIMARY KEY,
     family_id      UUID        NOT NULL,
     user_id        INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     token_hash     CHAR(64)    NOT NULL,
     issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
     expires_at     TIMESTAMPTZ NOT NULL,
     revoked_at     TIMESTAMPTZ NULL,
     revoked_reason VARCHAR(40) NULL,
     replaced_by    UUID        NULL,
     CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.userTokens} (
     id          UUID        PRIMARY KEY,
     user_id     INTEGER     NOT NULL REFERENCES ${T.users} (id) ON DELETE CASCADE,
     purpose     VARCHAR(24) NOT NULL,
     token_hash  CHAR(64)    NOT NULL,
     expires_at  TIMESTAMPTZ NOT NULL,
     consumed_at TIMESTAMPTZ NULL,
     created_by  INTEGER     NULL,
     created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
     CONSTRAINT uq_user_tokens_hash UNIQUE (token_hash)
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.rbacRepairs} (
     id         VARCHAR(64) PRIMARY KEY,
     applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.permissionSeedLog} (
     permission_id VARCHAR(64)  PRIMARY KEY,
     seeded_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.loginAttempts} (
     identifier        VARCHAR(190) PRIMARY KEY,
     attempts          INTEGER      NOT NULL DEFAULT 0,
     window_started_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
     locked_until      TIMESTAMPTZ  NULL
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.auditLogs} (
     id               BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     ts               TIMESTAMPTZ  NOT NULL DEFAULT now(),
     event            VARCHAR(64)  NOT NULL,
     actor_id         INTEGER      NULL,
     actor            VARCHAR(190) NULL,
     actor_company_id INTEGER      NULL,
     company_id       INTEGER      NULL,
     target_user_id   INTEGER      NULL,
     detail           JSONB        NOT NULL DEFAULT '{}'::jsonb
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.companyFeatures} (
     company_id INTEGER     NOT NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     feature_id VARCHAR(64) NOT NULL,
     enabled_by INTEGER     NULL,
     enabled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     PRIMARY KEY (company_id, feature_id)
   )`,

  `ALTER TABLE ${T.companies} ADD COLUMN IF NOT EXISTS features_seeded BOOLEAN NOT NULL DEFAULT FALSE`,

  `CREATE TABLE IF NOT EXISTS ${T.companyRoles} (
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     company_id  INTEGER      NOT NULL REFERENCES ${T.companies} (id) ON DELETE CASCADE,
     name        VARCHAR(50)  NOT NULL,
     description VARCHAR(255) NULL,
     created_by  INTEGER      NULL,
     created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
     updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
     CONSTRAINT uq_company_roles_name UNIQUE (company_id, name)
   )`,

  `ALTER TABLE ${T.companyRoles} ADD COLUMN IF NOT EXISTS builtin_role VARCHAR(50) NULL`,

  `ALTER TABLE ${T.companyRoles} ADD COLUMN IF NOT EXISTS modified_by INTEGER NULL`,
  `ALTER TABLE ${T.companyRoles} ADD COLUMN IF NOT EXISTS modified_at TIMESTAMPTZ NULL`,

  `CREATE TABLE IF NOT EXISTS ${T.permissions} (
     id            VARCHAR(100) PRIMARY KEY,
     feature       VARCHAR(64)  NULL,
     platform_only BOOLEAN      NOT NULL DEFAULT FALSE,
     admin_only    BOOLEAN      NOT NULL DEFAULT FALSE
   )`,

  `CREATE TABLE IF NOT EXISTS ${T.companyRolePermissions} (
     role_id       INTEGER      NOT NULL REFERENCES ${T.companyRoles} (id) ON DELETE CASCADE,
     permission_id VARCHAR(100) NOT NULL,
     PRIMARY KEY (role_id, permission_id)
   )`,

  `ALTER TABLE ${T.users} ADD COLUMN IF NOT EXISTS custom_role_id INTEGER NULL
     REFERENCES ${T.companyRoles} (id) ON DELETE RESTRICT`,
];

const INDEXES = [
  `CREATE INDEX IF NOT EXISTS idx_users_company ON ${T.users} (company_id)`,
  `CREATE INDEX IF NOT EXISTS idx_groups_creator ON ${T.groups} (creator_id)`,
  `CREATE INDEX IF NOT EXISTS idx_group_users_user ON ${T.groupUsers} (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_dashboards_company ON ${T.dashboards} (company_id)`,
  `CREATE INDEX IF NOT EXISTS idx_dashboards_creator ON ${T.dashboards} (created_by)`,
  `CREATE INDEX IF NOT EXISTS idx_company_dashboards_dashboard ON ${T.companyDashboards} (dashboard_id)`,
  `CREATE INDEX IF NOT EXISTS idx_dashboard_access_dashboard ON ${T.dashboardAccess} (dashboard_id)`,
  `CREATE INDEX IF NOT EXISTS idx_group_dashboard_access_dashboard ON ${T.groupDashboardAccess} (dashboard_id)`,
  `CREATE INDEX IF NOT EXISTS idx_user_data_scope_user ON ${T.userDataScope} (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON ${T.refreshTokens} (family_id)`,
  `CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON ${T.refreshTokens} (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expiry ON ${T.refreshTokens} (expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_user_tokens_user ON ${T.userTokens} (user_id, purpose)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_ts ON ${T.auditLogs} (ts DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_company ON ${T.auditLogs} (company_id, ts DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON ${T.auditLogs} (actor_id, ts DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_target_user ON ${T.auditLogs} (target_user_id, ts DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_users_custom_role ON ${T.users} (custom_role_id) WHERE custom_role_id IS NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_company_roles_builtin ON ${T.companyRoles} (company_id, builtin_role)
     WHERE builtin_role IS NOT NULL`,
];

const guard = (name: string, table: string, ddl: string) => `DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '${name}') THEN
    EXECUTE 'ALTER TABLE ${table} ADD CONSTRAINT ${name} ${ddl.replace(/'/g, "''")} NOT VALID';
  END IF;
  BEGIN
    EXECUTE 'ALTER TABLE ${table} VALIDATE CONSTRAINT ${name}';
  EXCEPTION WHEN others THEN
    RAISE WARNING 'rbac: % not validated: %', '${name}', SQLERRM;
  END;
END $$`;

const INTEGRITY = [
  guard('chk_company_roles_builtin', T.companyRoles,
    `CHECK (builtin_role IS NULL OR (builtin_role = 'USER' AND name = builtin_role))`),

  `CREATE UNIQUE INDEX IF NOT EXISTS uq_company_roles_id_company ON ${T.companyRoles} (id, company_id)`,
  guard('fk_users_custom_role_company', T.users,
    `FOREIGN KEY (custom_role_id, company_id) REFERENCES ${T.companyRoles} (id, company_id)`),

  guard('chk_users_custom_role_member', T.users, `CHECK (custom_role_id IS NULL OR role = 'USER')`),

  guard('fk_company_role_permissions_permission', T.companyRolePermissions,
    `FOREIGN KEY (permission_id) REFERENCES ${T.permissions} (id) ON DELETE CASCADE`),

  `CREATE OR REPLACE FUNCTION rbac_guard_company_role_permission() RETURNS trigger AS $$
   BEGIN
     IF EXISTS (SELECT 1 FROM ${T.permissions} p
                 WHERE p.id = NEW.permission_id AND (p.platform_only OR p.admin_only)) THEN
       RAISE EXCEPTION 'permission % cannot be held by a company role', NEW.permission_id
         USING ERRCODE = 'check_violation';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `DROP TRIGGER IF EXISTS trg_company_role_permission_guard ON ${T.companyRolePermissions}`,
  `CREATE TRIGGER trg_company_role_permission_guard
     BEFORE INSERT OR UPDATE ON ${T.companyRolePermissions}
     FOR EACH ROW EXECUTE FUNCTION rbac_guard_company_role_permission()`,

  `CREATE OR REPLACE FUNCTION rbac_forbid_builtin_custom_role() RETURNS trigger AS $$
   BEGIN
     IF NEW.custom_role_id IS NOT NULL AND EXISTS (
          SELECT 1 FROM ${T.companyRoles} r WHERE r.id = NEW.custom_role_id AND r.builtin_role IS NOT NULL) THEN
       RAISE EXCEPTION 'role % is a built-in copy and cannot be assigned', NEW.custom_role_id
         USING ERRCODE = 'check_violation';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `DROP TRIGGER IF EXISTS trg_users_custom_role_guard ON ${T.users}`,
  `CREATE TRIGGER trg_users_custom_role_guard
     BEFORE INSERT OR UPDATE OF custom_role_id ON ${T.users}
     FOR EACH ROW EXECUTE FUNCTION rbac_forbid_builtin_custom_role()`,
];

export { T, TABLES, INDEXES, INTEGRITY };
